name: todo_list
description: A new Flutter project.

#打包命令：flutter build apk --target-platform android-arm --split-per-abi

version: 1.0.7+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #国际化
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #intl语言包
  intl_translation: ^0.17.5


  #网络请求
  dio: ^2.1.2
  #本地存储
  shared_preferences: ^0.5.2
  #状态管理
  provider: ^3.0.0+1
  #单元测试
  test: ^1.6.0
  #滑动控件
  carousel_slider: ^1.3.0
  #环形列表
  circle_list: ^0.1.3
#  #intl语言包
#  intl: ^0.16.0
  #本地数据库
  sqflite: ^1.1.6
  #取色框
  flutter_colorpicker: ^0.2.5
  #图片缓存
  cached_network_image: ^1.1.0
  #图片选取
  image_picker: ^0.6.0+16
  #权限申请
  permission_handler: ^3.2.0
  #路径获取
  path_provider: ^1.1.2
  #图片裁剪
  image_crop: ^0.3.0
  #svg----这个控件真是饱受挫折呀！
  flutter_svg: ^0.13.1
  #获取package信息
  package_info: ^0.4.0+5
  #网页
  flutter_webview_plugin: ^0.3.5
  #上拉加载
  pull_to_refresh: ^1.5.0
  #看图片
  photo_view: ^0.4.2
  #url,可以用来打开应用商店
  url_launcher: ^5.1.0
  #打开文件，android更新下载安装包用
  open_file: ^2.0.3
  #flare动画
  flare_flutter: ^1.5.5
  #加密
  encrypt: ^3.2.0


# The following section is specific to Flutter.
flutter:

  assets:
    - images/
    - images/weather/
    - local_json/
    - svgs/
    - flrs/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

